language: python
dist: bionic
python:
  - "3.8.3"
services:
  - docker
install:
    - docker build -t xdusongwei/aiorocksdb .
script:
  - docker run xdusongwei/aiorocksdb /bin/sh -c "cd /app && coverage run -m pytest && codecov"
