language: python
dist: bionic
python:
- 3.8.3
services:
- docker
install:
- docker build -t xdusongwei/aiorocksdb .
script:
- docker run --name test xdusongwei/aiorocksdb /bin/bash -c "coverage run -m pytest"
- docker cp test:/home/travis/build/xdusongwei/aiorocksdb/.coverage .
- pip install codecov coveralls
- codecov
- coveralls
