language: python
dist: bionic
python:
- 3.8.3
services:
- docker
install:
- docker build --quiet -t travis/aiorocksdb .
script:
- docker run --name ci travis/aiorocksdb /bin/bash -c "coverage run -m pytest"
- docker cp ci:/home/travis/build/xdusongwei/aiorocksdb/.coverage .
- pip --quiet install codecov coveralls
- test -f .coverage && codecov
- test -f .coverage && coveralls
